name: Sync Template
permissions:
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    schedule:
        - cron: "0 2 * * *" # every night at 2:00 UTC

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              # for now, pin cookiecutter version, due to https://github.com/cruft/cruft/issues/166
              run: python -m pip install --upgrade cruft "cookiecutter<2" pre-commit toml
            - name: Find Latest Tag
              uses: oprypin/find-latest-tag@v1.1.0
              id: get-latest-tag
              with:
                  repository: lamin/cookiecutter-py
                  releases-only: false
                  sort-tags: true
                  regex: '^v\d+\.\d+\.\d+$' # vX.X.X

            - name: Sync
              run: cruft update --checkout ${{ steps.get-latest-tag.outputs.tag }} --skip-apply-ask --project-dir .
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v4
              with:
                  commit-message: Automated template update from lamin's cookiecutter
                  branch: template-update
                  title: Automated template update from lamin's cookiecutter
                  body: |
                      A new version of [lamin's cookiecutter template](https://github.com/lamin/cookiecutter-py/releases)
                      got released. This PR adds all new changes to your repository and helps to to stay in sync with
                      the latest best-practice template maintained by the scverse team.

                      **If a merge conflict arised, a `.rej` file with the rejected patch is generated. You'll need to
                      manually merge these changes.**
